"""Build the live examples of the report package, in English and Russian, and check them.

    py docs/examples/sample-report/make_sample.py

Uses gak.report exactly like the CLI does: new_version -> write body and assets -> build.
For each language (en/, ru/) two reports on made-up numbers, both in the fixed skeleton of
DESIGN.md section 6:

    sample            a full review (kind "full"): v001, v002 made with from_version=1, v003 a draft
    sample-question   a question report (kind "question"): v001

The standard tables are rendered by gak.metrics / gak.sequences from made-up results, the
same code `ga.py keymetrics / dropoff / ordinals / leaving --format html` runs. Texts live in
sample_text.py. Output: <lang>/analytics/reports/ next to this file (the site publishes en/
under /examples/ and ru/ under /ru/examples/). The script then validates the output: tags
balance, no placeholders left, sane sizes, artifact.html without a document shell, every
component present, and that the builder refuses what it must refuse (placeholders,
structure). Exit code 0 = all passed.
"""
from __future__ import annotations

import json
import re
import shutil
import sqlite3
import struct
import sys
import zlib
from html.parser import HTMLParser
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[2]
sys.path.insert(0, str(REPO / "kit"))
sys.path.insert(0, str(HERE))

from gak import metrics, sequences  # noqa: E402
from gak.report import ReportError, build, build_index, charts as ch, new_version  # noqa: E402
from sample_text import TEXT  # noqa: E402

SLUG = "sample"
QSLUG = "sample-question"
LANGS = ("en", "ru")
CONFIG = """[project]
name = "Sample Game"
report_language = "{lang}"
platforms = ["android"]

[database]
path = "data/analytics.db"
"""
GITIGNORE = "# Generated by make_sample.py; only reports/ is kept as the live example.\ndata/\nreports/**/work/\n"


# --------------------------------------------------------------------------- fake inputs

def png(width: int, height: int, pixel) -> bytes:
    """Minimal RGB PNG writer: pixel(x, y) -> (r, g, b)."""
    rows = b"".join(b"\0" + bytes(c for x in range(width) for c in pixel(x, y)) for y in range(height))

    def chunk(kind: bytes, data: bytes) -> bytes:
        return struct.pack(">I", len(data)) + kind + data + struct.pack(">I", zlib.crc32(kind + data) & 0xFFFFFFFF)

    signature = bytes([137, 80, 78, 71, 13, 10, 26, 10])
    header = struct.pack(">IIBBBBB", width, height, 8, 2, 0, 0, 0)
    return signature + chunk(b"IHDR", header) + chunk(b"IDAT", zlib.compress(rows, 9)) + chunk(b"IEND", b"")


def fake_console(accent: tuple[int, int, int], bars: list[int]):
    """A pretend dashboard screenshot: title bar, card, a few columns."""
    def pixel(x, y):
        if y < 34:
            return (38, 42, 51)
        if 20 <= x < 620 and 54 <= y < 330:
            base_y = 310
            for i, h in enumerate(bars):
                x0 = 60 + i * 64
                if x0 <= x < x0 + 36 and base_y - h <= y < base_y:
                    return accent
            if y in (base_y, base_y - 80, base_y - 160) and 50 <= x < 600:
                return (225, 226, 230)
            return (255, 255, 255)
        return (241, 243, 246)
    return pixel


def fake_db(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    con = sqlite3.connect(path)
    con.executescript("""
        CREATE TABLE events (id INTEGER PRIMARY KEY, date TEXT, event_name TEXT);
        CREATE TABLE installations (id INTEGER PRIMARY KEY, date TEXT, publisher_name TEXT);
        CREATE TABLE meta (key TEXT PRIMARY KEY, value TEXT);
    """)
    con.executemany("INSERT INTO events (date, event_name) VALUES (?, ?)",
                    [(f"2026-09-{d:02d}", "level_start") for d in range(1, 22) for _ in range(d % 4 + 1)])
    con.executemany("INSERT INTO installations (date, publisher_name) VALUES (?, ?)",
                    [(f"2026-09-{d:02d}", "Google Ads" if d > 16 else "") for d in range(1, 22)])
    con.execute("INSERT INTO meta VALUES ('app_name', 'Sample Game')")
    con.execute("INSERT INTO meta VALUES ('appmetrica.sample_rate', '0.1')")
    con.commit()
    con.close()


# --------------------------------------------------------------------------- standard tables

def fake_population(n: int) -> metrics.Population:
    devices = {f"d{i}": metrics.Device("2026-09-01", "1.0.8" if i < 118 else "1.1.0", "US") for i in range(n)}
    return metrics.Population(devices, "v_players", "2026-09-01", "2026-09-20", 0.1, "2026-09-21")


def fake_key_metrics() -> metrics.KeyMetrics:
    g = ["1.0.8", "1.1.0", metrics.ALL]

    def row(key, unit, values, n=None, median=None, estimate=False):
        return metrics.Row(key, unit, dict(zip(g, values)), dict(zip(g, n or [])), dict(zip(g, median or [])),
                           estimate)
    rows = [
        row("players", "count", [118, 94, 212]),
        row("players_est", "count", [1180, 940, 2120], estimate=True),
        row("d1", "pct", [31.2, 35.1, 32.8], n=[109, 77, 186]),
        row("d3", "pct", [12.4, 14.0, 13.0], n=[97, 57, 154]),
        row("d7", "pct", [5.1, None, 5.1], n=[79, 0, 79]),
        row("playtime", "min", [11.8, 12.6, 12.2], median=[5.3, 5.4, 5.3]),
        row("sessions", "num", [2.9, 3.1, 3.0], median=[2, 2, 2]),
        row("session_len", "min", [4.1, 4.1, 4.1], median=[1.9, 2.0, 1.9]),
        row("ads_interstitial", "num", [3.4, 3.6, 3.5]),
        row("ads_rewarded", "num", [0.6, 0.9, 0.7]),
        row("arpu", "usd", [0.012, 0.015, 0.0133]),
        row("revenue", "usd", [1.42, 1.41, 2.83]),
        row("revenue_est", "usd", [14.2, 14.1, 28.3], estimate=True),
    ]
    return metrics.KeyMetrics("version", g, rows, fake_population(212), 600, None, [])


def fake_dropoff(t: dict) -> metrics.Dropoff:
    total, rows = 212, []

    def chain(section, items):
        previous = total
        rows.append(metrics.DropRow(section, "", total, None, None, 100.0))
        for label, reached, seconds in items:
            lost = previous - reached
            rows.append(metrics.DropRow(section, label, reached, lost, 100.0 * lost / previous,
                                        100.0 * reached / total, seconds))
            previous = reached
    steps = t["steps"]
    chain("steps", [(steps[0], 207, None), (steps[1], 188, None), (steps[2], 184, None), (steps[3], 179, None),
                    (steps[4], 141, None)])
    alive = [188, 171, 160, 151, 142, 136, 129, 125, 119, 110, 106, 101, 98, 95, 91, 88, 85, 83, 80, 78]
    chain("time", [(f"{s // 60}:{s % 60:02d}", a, s) for s, a in zip(range(30, 601, 30), alive)])
    timing = {steps[0]: (0.4, 1.1, 38.0), steps[1]: (7.8, 24.0, 3899.0), steps[2]: (10.7, 31.0, 1357.0)}
    for row in rows:
        if row.section == "steps" and row.label in timing:
            row.sec_median, row.sec_p90, row.sec_max = timing[row.label]
    return metrics.Dropoff(rows, fake_population(total), "all", 600, "v_first_steps", [])


def fake_ordinals(t: dict) -> sequences.Ordinals:
    first, second = t["ordinals"]
    data = {first: ([180, 130, 95, 70, 51], [42, 145, 262, 364, 480], [140, 282, 489, 684, 908]),
            second: ([150, 112, 83, 58, 41], [93, 211, 317, 410, 489], [230, 411, 645, 983, 1121])}
    rows = [sequences.OrdinalRow(label, n, dev, dev + n * 7, 100.0 * dev / 212, med, mean)
            for label, (devs, meds, means) in data.items()
            for n, (dev, med, mean) in enumerate(zip(devs, meds, means), 1)]
    return sequences.Ordinals(rows, fake_population(212), f"{first}, {second}", 5, False, [])


def fake_leaving(t: dict) -> sequences.Leaving:
    a, b, c, d = t["leaving"]
    rows = [sequences.LeavingRow(a, 190, 120, 56, 30, 25, 6), sequences.LeavingRow(b, 620, 150, 61, 34, 22, 2),
            sequences.LeavingRow(c, 540, 131, 85, 43, 30, 1), sequences.LeavingRow(d, 700, 180, 41, 30, 0, 0)]
    return sequences.Leaving(rows, fake_population(212), "…", 20, ["app_pause"], ["app_resume"], [])


# --------------------------------------------------------------------------- charts

ORGANIC = [26, 27, 25, 29, 24, 28, 27, 26, 30, 25, 27, 26, 28, 25, 11, 10, 9, 12, 10, 11, 9]
PAID = [0] * 16 + [7, 20, 14, 12, 31]
UNKNOWN = [2, 1, 3, 2, 2, 1, 2, 3, 1, 2, 2, 1, 3, 2, 1, 1, 4, 5, 3, 2, 7]
REVENUE = [1.17, 0.97, 0.76, 0.26, 0.23, 0.19, 0.16, 0.14, 0.12, 0.11, 0.1, 0.09, 0.08, 0.07, 0.06,
           0.06, 0.05, 0.05, 0.04, 0.04, 0.04, 0.04, 0.03, 0.03, 0.03, 0.02, 0.02, 0.02, 0.02, 0.01,
           0.01, 0.01, 0.01, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


def make_charts(lang: str) -> dict[str, str]:
    c = TEXT[lang]["charts"]
    day = c["day"]
    days = [day(d) for d in range(1, 22)]
    margin = [-3.2, -1.5, 0.4, 2.1, -0.8, 1.6, 3.3, -2.4, 0.9, 1.2]
    return {
        "daily": ch.stacked_bars(
            days, [(c["organic"], "s1", ORGANIC), (c["paid"], "s2", PAID), (c["unknown"], "s-unk", UNKNOWN)],
            bands=[ch.annotate_band(day(15), None, c["band"])], lang=lang, title=c["daily_title"],
            x_label=c["daily_x"]),
        "matches": ch.grouped_bars(
            ["0", "1", "2", "3–5", "6–10", "11+"],
            [(f"{c['build']} 1.0.8", "s-old", [16.2, 32.4, 13.2, 19.1, 13.2, 5.9]),
             (f"{c['build']} 1.1.0", "s1", [20.8, 34.0, 9.4, 20.8, 9.4, 5.7])],
            unit="%", lang=lang, title=c["matches_title"], x_label=c["matches_x"]),
        "networks": ch.grouped_bars(
            c["weeks"],
            [(f"{TEXT[lang]['network']} {n}", f"s{i + 1}", vals) for i, (n, vals) in enumerate([
                ("A", [34, 31, 29]), ("B", [22, 24, 21]), ("C", [15, 14, 18]),
                ("D", [12, 13, 12]), ("E", [10, 11, 12]), ("F", [7, 7, 8])])],
            unit="%", lang=lang, title=c["networks_title"], height=260, x_label=c["networks_x"]),
        "revenue": ch.ranked_bars(
            REVENUE, labels=[f"{c['player']} {i + 1}" for i in range(len(REVENUE))], highlight_top=5,
            mean_line=True, median_line=True, unit="$", lang=lang, title=c["revenue_title"], x_label=c["revenue_x"]),
        "reasons": ch.hbars(
            c["reasons"], [25, 16, 9, 6, 3], unit="%", lang=lang, highlight={0: "s-bad"},
            title=c["reasons_title"], x_label=c["reasons_x"]),
        "margin": ch.bar(
            [day(d) for d in range(12, 22)], margin, unit="$", lang=lang,
            highlight={i: ("s-good" if v >= 0 else "s-bad") for i, v in enumerate(margin)},
            title=c["margin_title"], x_label=c["margin_x"]),
        "retention": ch.line(
            days, [(f"{c['build']} 1.0.8", "s-old", [31, 30, 32, 29, 30, 31, 28, 30, 29, 31, 30, 29, 30, 31] + [None] * 7),
                   (f"{c['build']} 1.1.0", "s1", [None] * 13 + [30, 33, 35, 34, 36, 35, 37, 36])],
            unit="%", lang=lang, ymax=50, bands=[ch.annotate_band(day(14), day(15), c["switch"])],
            annotations=[(day(17), c["ua_start"])], title=c["retention_title"], x_label=c["retention_x"]),
    }


# --------------------------------------------------------------------------- writing a version

def write_assets(vdir: Path, lang: str, names: list[str] | None = None) -> None:
    t = TEXT[lang]
    for name, svg in make_charts(lang).items():
        if names is None or name in names:
            (vdir / "assets" / f"{name}.svg").write_text(svg, encoding="utf-8", newline="\n")
    if names is not None:
        return
    fragments = {
        "keymetrics.html": metrics.render_key_metrics(fake_key_metrics(), "html", lang),
        "ordinals.html": sequences.render_ordinals(fake_ordinals(t), "html", lang),
        "leaving.html": sequences.render_leaving(fake_leaving(t), "html", lang),
    }
    drop = fake_dropoff(t)
    fragments["dropoff.html"] = metrics.render_dropoff(drop, "html", lang)
    fragments["dropoff.svg"] = metrics.dropoff_svg(drop, lang)
    for name, text in fragments.items():
        (vdir / "assets" / name).write_text(text, encoding="utf-8", newline="\n")
    (vdir / "assets" / "console.png").write_bytes(png(640, 360, fake_console((42, 120, 214), [120, 180, 150, 210, 90])))
    (vdir / "assets" / "console_a.png").write_bytes(png(640, 360, fake_console((235, 104, 52), [60, 140, 200, 170, 110])))
    (vdir / "assets" / "console_b.png").write_bytes(png(640, 360, fake_console((12, 163, 12), [200, 90, 60, 150, 180])))


def body(lang: str) -> str:
    networks = ch.legend_html([(f"{TEXT[lang]['network']} {n}", f"s{i + 1}") for i, n in enumerate("ABCDEF")])
    return TEXT[lang]["body"].replace("LEGEND_NETWORKS", networks)


def write_md(vdir: Path, lang: str, label: str, until: str) -> None:
    """report.md: the short version for chat and messengers."""
    (vdir / "report.md").write_text(TEXT[lang]["md"].format(until=until, label=label), encoding="utf-8",
                                    newline="\n")


def update_meta(vdir: Path, **fields) -> None:
    path = vdir / "meta.json"
    meta = json.loads(path.read_text(encoding="utf-8"))
    meta.update(fields)
    path.write_text(json.dumps(meta, ensure_ascii=False, indent=2) + "\n", encoding="utf-8", newline="\n")


def write_src(vdir: Path, text: str) -> None:
    (vdir / "report.src.html").write_text(text, encoding="utf-8", newline="\n")


def expect_error(label: str, fn, *needles: str) -> None:
    try:
        fn()
    except ReportError as exc:
        missing = [n for n in needles if n not in str(exc)]
        if missing:
            raise SystemExit(f"FAIL {label}: error text lacks {missing}:\n{exc}")
        print(f"ok   {label}: refused -> {str(exc).splitlines()[0][:100]}")
        return
    raise SystemExit(f"FAIL {label}: no error raised")


# --------------------------------------------------------------------------- checks

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "source", "track", "wbr"}
BLOCK = {"address", "article", "aside", "blockquote", "div", "dl", "figure", "footer", "form", "h1", "h2", "h3",
         "h4", "h5", "h6", "header", "hr", "main", "nav", "ol", "p", "pre", "section", "table", "ul"}


class TagBalance(HTMLParser):
    """Every non-void tag closes in order; no block element inside <p> (a browser would split it)."""

    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.stack: list[tuple[str, int]] = []
        self.errors: list[str] = []

    def handle_starttag(self, tag, attrs):
        if tag in VOID:
            return
        if tag in BLOCK and any(t == "p" for t, _ in self.stack):
            self.errors.append(f"line {self.getpos()[0]}: <{tag}> inside <p>")
        self.stack.append((tag, self.getpos()[0]))

    def handle_endtag(self, tag):
        if tag in VOID:
            return
        if not self.stack:
            self.errors.append(f"line {self.getpos()[0]}: </{tag}> with nothing open")
        elif self.stack[-1][0] != tag:
            self.errors.append(f"line {self.getpos()[0]}: </{tag}> closes <{self.stack[-1][0]}> "
                               f"opened at line {self.stack[-1][1]}")
            if any(t == tag for t, _ in self.stack):
                while self.stack and self.stack.pop()[0] != tag:
                    pass
        else:
            self.stack.pop()

    def finish(self) -> list[str]:
        self.close()
        return self.errors + [f"<{t}> opened at line {n} never closed" for t, n in self.stack]


def check_file(path: Path, lang: str, *, artifact: bool = False, min_kb: int = 5, max_kb: int = 3000) -> list[str]:
    text = path.read_text(encoding="utf-8")
    parser = TagBalance()
    parser.feed(text)
    problems = parser.finish()
    if "{{" in text or "}}" in text:
        problems.append("placeholder braces left in the output")
    size_kb = path.stat().st_size / 1024
    if not min_kb <= size_kb <= max_kb:
        problems.append(f"size {size_kb:.0f} KB outside {min_kb}..{max_kb} KB")
    low = text.lower()
    if artifact:
        if not text.startswith("<title>"):
            problems.append("artifact.html must start with <title>")
        for shell in re.findall(r"<(!doctype|html|head|body)[\s>]", low):
            problems.append(f"artifact.html contains <{shell}>")
    elif path.name == "report.html":
        for need in ("<!doctype html>", f'<html lang="{lang}">', "<style>", "fonts.googleapis.com"):
            if need not in low:
                problems.append(f"report.html lacks {need}")
    print(f"{'ok  ' if not problems else 'FAIL'} {path.relative_to(HERE)}  {size_kb:.1f} KB")
    for p in problems:
        print(f"       - {p}")
    return problems


COMPONENTS = [
    'class="wrap"', 'class="masthead"', 'class="eyebrow"', "<h1>", 'class="standfirst"', 'class="tiles"',
    'class="tile warn"', 'class="tile ad"', 'class="tile good"', 'class="k"', 'class="v"', 'class="n"',
    'class="answers"', 'class="ans"', 'class="q"', 'class="lede"', 'class="note"', 'class="calc"',
    "<figure>", 'class="figbox"', 'class="legend"', "<figcaption>", 'class="shot"', 'class="tag"',
    'class="frame"', 'class="shots2"', 'class="tablebox"', 'class="n ok"', 'class="n bad"',
    'class="total"', 'class="tnote"', 'class="cards"', 'class="card hot"', 'class="card adc"',
    'class="card okc"', 'class="cnt"', 'class="acts"', 'class="act"', 'class="why"', 'class="method"',
    "data:image/png;base64,", 'class="band"', 'class="refl"', 'class="refl alt"', 'class="ln s1"',
    'class="dot s1"', "mk s-good", "mk s-bad", "mk s-unk", "mk s-old", "mk s6", 'class="hit"',
    # the fixed skeleton
    'class="toc"', 'class="block" id="summary"', 'class="bn"', 'class="hyps"', 'class="hyp" id="h1"',
    'class="hid"', 'class="conf high"', 'class="conf mid"', 'class="conf low"', 'class="basis"',
    'class="test"', 'class="eff"', 'class="measure"', 'class="interp"', 'class="kpi"', 'class="drop"',
    'class="n est"', '<tr class="est">', "Retention D1",
]


def check_components(lang: str, index: Path, *paths: Path) -> list[str]:
    text = "".join(p.read_text(encoding="utf-8") for p in (*paths, index))
    missing = [n for n in COMPONENTS + TEXT[lang]["needles"] if n not in text]
    names = ", ".join(p.parent.parent.name + "/" + p.parent.name for p in paths)
    print(f"{'ok  ' if not missing else 'FAIL'} every component, chart class and label present in {names} + index")
    return [f"missing {m}" for m in missing]


# --------------------------------------------------------------------------- one language

def build_language(lang: str) -> list[str]:
    t = TEXT[lang]
    analytics = HERE / lang / "analytics"
    print(f"\n[{lang}] {analytics.relative_to(HERE)}")
    for generated in (analytics / "reports", analytics / "data"):
        if generated.exists():
            shutil.rmtree(generated)
    analytics.mkdir(parents=True, exist_ok=True)
    (analytics / "analytics.toml").write_text(CONFIG.format(lang=lang), encoding="utf-8", newline="\n")
    (analytics / ".gitignore").write_text(GITIGNORE, encoding="utf-8", newline="\n")
    fake_db(analytics / "data" / "analytics.db")

    expect_error("bad slug", lambda: new_version(analytics, "Bad Slug", "x"), "bad report slug")
    expect_error("bad kind", lambda: new_version(analytics, SLUG, "x", kind="essay"), "unknown report kind")

    v1 = new_version(analytics, SLUG, t["title"], kind="full")
    scaffold = (v1 / "report.src.html").read_text(encoding="utf-8")
    if t["scaffold_word"] not in scaffold or "__T_" in scaffold or 'id="hypotheses"' not in scaffold:
        raise SystemExit(f"FAIL [{lang}] the full scaffold is not localised or lacks its blocks")
    print("ok   full scaffold: blocks named in the report language")
    expect_error("scaffold without data window", lambda: build(analytics, SLUG), "data_window.since", "is empty")
    write_src(v1, body(lang))
    write_assets(v1, lang)
    write_md(v1, lang, "v001", t["until_v1"])
    update_meta(v1, subtitle=t["subtitle"], question=t["question"],
                data_window={"since": "2026-09-01", "until": "2026-09-20"}, sources_used=t["sources"])
    r1 = build(analytics, SLUG)
    print(f"ok   built {r1.relative_to(HERE)}")
    expect_error("rebuild of a built version", lambda: build(analytics, SLUG, 1), "final", "--from v1")

    v2 = new_version(analytics, SLUG, t["title"], from_version=1)
    good = (v2 / "report.src.html").read_text(encoding="utf-8")
    write_src(v2, good.replace("{{svg:assets/daily.svg}}", "{{svg:assets/missing.svg}} {{img:assets/x.bmp}}")
              .replace("{{meta:question}}", "{{meta:nope}} {{foo:bar}} {{ stray"))
    expect_error("unresolved placeholders", lambda: build(analytics, SLUG, 2),
                 "missing asset assets/missing.svg", "unsupported image type .bmp", "no field 'nope'",
                 "unknown placeholder", "stray")
    write_src(v2, good.replace('<section class="block" id="countries">', '<section class="block" id="geo">')
              .replace('<a href="#revenue-ads">3.1</a>', '<a href="#nowhere">3.1</a>')
              .replace(t["eff_prefix"], t["eff_broken"], 1)
              .replace('<p class="why">→ <a href="#h3">H3</a></p>', t["why_broken"])
              .replace(t["conf_low"], "")
              .replace('<h3 id="summary-metrics">', '<h3 id="summary-answers">'))
    expect_error("structure of a full review", lambda: build(analytics, SLUG, 2),
                 "structure problem", "block #countries is missing", "link #nowhere points to no id",
                 "no link to a hypothesis", "no confidence mark", "no expected effect",
                 'id "summary-answers" is used 2 times')
    write_src(v2, good.replace("</header>\n", t["changes"], 1))
    update_meta(v2, data_window={"since": "2026-09-01", "until": "2026-09-21"})
    write_md(v2, lang, "v002", t["until_v2"])
    r2 = build(analytics, SLUG, 2)
    kind = json.loads((v2 / "meta.json").read_text(encoding="utf-8"))["kind"]
    print(f"ok   built {r2.relative_to(HERE)} (from v001, kind kept: {kind})")
    v3 = new_version(analytics, SLUG, "", from_version=2)
    print(f"ok   draft {v3.relative_to(HERE)} left unbuilt on purpose")

    q1 = new_version(analytics, QSLUG, t["q_title"], kind="question")
    write_assets(q1, lang, ["revenue"])
    update_meta(q1, subtitle=t["q_subtitle"], question=t["q_question"],
                data_window={"since": "2026-09-17", "until": "2026-09-21"}, sources_used=t["q_sources"])
    write_src(q1, t["question_body"].replace('<section class="block" id="actions">', '<section class="block" id="todo">'))
    expect_error("question report without recommendations", lambda: build(analytics, QSLUG),
                 "block #actions is missing")
    write_src(q1, t["question_body"])
    rq = build(analytics, QSLUG)
    print(f"ok   built {rq.relative_to(HERE)} (question)")
    index = build_index(analytics)

    problems: list[str] = []
    for vdir in (v1, v2, q1):
        problems += check_file(vdir / "report.html", lang)
        problems += check_file(vdir / "artifact.html", lang, artifact=True)
    problems += check_file(index, lang, min_kb=1)
    problems += check_components(lang, index, r2, rq)
    meta2 = json.loads((v2 / "meta.json").read_text(encoding="utf-8"))
    snap = meta2.get("db_snapshot") or {}
    if (snap.get("tables", {}).get("events", {}).get("max_date") != "2026-09-21" or meta2.get("previous_version") != 1
            or meta2.get("kind") != "full" or snap.get("sample_rate") != 0.1 or meta2.get("language") != lang):
        problems.append(f"meta.json of v002 is wrong: {meta2}")
    idx = index.read_text(encoding="utf-8")
    for need in ("sample/v002/report.html", "sample/v001/report.html", "sample/v002/report.md",
                 "sample-question/v001/report.html"):
        if need not in idx:
            problems.append(f"index.html lacks {need}")
    return [f"[{lang}] {p}" for p in problems]


# --------------------------------------------------------------------------- main

def main() -> int:
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8")
        except (AttributeError, ValueError):
            pass
    assert ch.fmt_num(1234.5, 1, "ru") == "1\N{NARROW NO-BREAK SPACE}234,5"
    assert ch.fmt_num(-1234.5, 1, "en") == "\N{MINUS SIGN}1,234.5"
    assert ch.fmt_money(0.13, 2, "ru") == "$0,13" and ch.fmt_pct(0.335, 0, "en", ratio=True) == "34%"
    print("ok   number formatting (ru / en)")
    problems: list[str] = []
    for lang in LANGS:
        problems += build_language(lang)
    for p in problems:
        print(f"FAIL {p}")
    print(f"\n{'ALL CHECKS PASSED' if not problems else f'{len(problems)} PROBLEM(S)'}; open "
          + ", ".join(str(HERE / lang / "analytics" / "reports" / "index.html") for lang in LANGS))
    return 0 if not problems else 1


if __name__ == "__main__":
    sys.exit(main())
